### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [HilaManor/AudioEditingCode#2]
Hi, Thanks for releasing this project! Would you mind adding a license? Thanks!

**Comment by HilaManor** [comment]
Hi, all inversion parts and unconditional code should be an MIT license (basically our addition in this paper), but since we use parts of AudioLDM code to load the audio into mel-spectrograms, and provide wrappers for AudioLDM, we added the CC BY-SA 4.0 license over the whole project (for simplicity's sake).

**Comment by fakerybakery** [comment]
Ah, amazing. Thanks!
